theme = "space-villain"
icons = "awesome5"

# Toggle floating
[[block]]
block = "custom"
command = "echo "
interval = "once"
on_click = "~/i3conf/i3/scripts/toggle_float.sh"

# Toggle tiling/tabbed
[[block]]
block = "custom"
cycle = ["echo  && i3-msg -q 'layout toggle split'", "echo  && i3-msg -q 'layout tabbed'"]
interval = "once"
#on_click = "<command>"

# Memory
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

# CPU
[[block]]
block = "cpu"
interval = 2
format = "{barchart} {utilization} {frequency}"
on_click = "gnome-system-monitor"

#[[block]]
#block = "temperature"
#collapsed = false
#chip = "k10temp-pci-00c3"
#format = "{average}"

[[block]]
block = "load"
interval = 2
format = "{1m}"

# VPN
[[block]]
block = "custom"
command = "$HOME/i3conf/i3status-rust/vpn.sh"
hide_when_empty = true
interval = 10

# Net
[[block]]
block = "net"
format = "{signal_strength}"
interval = 5

# Music
[[block]]
block = "music"
buttons = ["play"]
hide_when_empty = true

# Bluetooth
[[block]]
block = "bluetooth"
mac = "60:AB:D2:3B:38:E5"
format = "Ninja"
format_unavailable = "Ninja X"
# hide_disconnected = true

# Sound
[[block]]
block = "sound"

# Battery
[[block]]
block = "battery"
interval = 60
format = "{percentage}"
on_click = "$HOME/.config/rofi/applets/menu/powermenu.sh"

# Backlight
[[block]]
block = "backlight"
invert_icons = true

# Notify
#[[block]]
#block = "notify"

#[[block]]
#block = "watson"

# Date time
[[block]]
block = "time"
interval = 1
format = "%a %b %d, <b>%H:%M:%S</b>"
on_click = "gsimplecal"
